---

- hosts: 127.0.0.1
  connection: local

  tasks:
    - name: create ssh directory
      become: yes
      file:
        path: "{{item}}"
        state: directory
        owner: root
        group: wheel
        mode: 0777
      with_items:
        - /etc/ssh
    - name: personal ssh config
      become: yes
      copy:
        src: files/ssh_config
        dest: /etc/ssh_config
    - name: personal ssh config in another location
      become: yes
      copy:
        src: files/ssh_config
        dest: /etc/ssh/ssh_config
    - name: add to sudoers without password
      become: yes
      lineinfile: >
        dest=/etc/sudoers
        regexp="{{ item.regexp }}"
        line="{{ item.line }}"
        state=present
        create=true
      with_items:
        - { regexp: '^ddcarr', line: 'ddcarr ALL=(ALL) NOPASSWD: ALL' }

  roles:
    - profile-all
    - profile-developer

  vars:
    - computername: godsmack
    - git_user_name: pdxdiver
    - git_user_email: ddcarr@gmail.com
    - aws_output_format: "{{ lookup('ini', 'output section=AWS_CLI file=~/.aws/aws_config') }}"
    - aws_region: "{{ lookup('ini', 'region section=AWS_CLI file=~/.aws/aws_config') }}"
    - aws_access_key_id: "{{ lookup('ini', 'access_key_id section=AWS_CLI file=~/.aws/aws_config') }}"
    - aws_secret_access_key: "{{ lookup('ini', 'secret_key section=AWS_CLI file=~/.aws/aws_config') }}"
