---

- name: tap caskroom/versions
  homebrew_tap: tap=caskroom/versions state=present

- name: install developer brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - wget

- name: install atom
  homebrew_cask: atom state=present
  
- name: install chefdk
  homebrew_cask: chefdk state=present
  
- name: install virtualbox
  homebrew_cask: virtualbox state=present
  
- name: install vagrant
  homebrew_cask: vagrant state=present
  
- name: install vagrant manager
  homebrew_cask: vagrant-manager state=present


